_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
architecture:
    value: GPT2
batch_size:
    value: 4
book_count:
    value: 10
dataset:
    value: Gutenberg
device:
    value: mps
epochs:
    value: 1
learning_rate:
    value: 0.0005
